/**
 * Build-time only. Nothing here ships and nothing is fetched at runtime:
 * this turns the public-domain Natural Earth 110m country set (via
 * world-atlas) into flat SVG path strings. Run it by hand when the map
 * geometry needs regenerating:
 *
 *   npm i --no-save world-atlas topojson-client topojson-simplify d3-geo
 *   node scripts/genworld.mjs > src/components/retro/worldPaths.ts
 */
import { readFileSync } from 'node:fs';
import { feature } from 'topojson-client';
import { presimplify, simplify, quantile } from 'topojson-simplify';
import { geoNaturalEarth1, geoPath } from 'd3-geo';

const WIDTH = 960;
const HEIGHT = 500;

const HIGHLIGHT = {
  Pakistan: 'PK',
  'Saudi Arabia': 'SA',
  Germany: 'DE',
  'United States of America': 'US',
  'United Kingdom': 'GB'
};

const raw = JSON.parse(
  readFileSync(new URL('../node_modules/world-atlas/countries-110m.json', import.meta.url))
);

// Weighted simplification: keeps coastlines readable at this size while
// dropping the vertex count that makes the inlined path enormous.
const pre = presimplify(raw);
const topo = simplify(pre, quantile(pre, 0.32));
const countries = feature(topo, topo.objects.countries);

const projection = geoNaturalEarth1().fitSize([WIDTH, HEIGHT], {
  type: 'Sphere'
});
const path = geoPath(projection);

/** Whole units at 960x500 is roughly one pixel: invisible here, much smaller. */
const shrink = (d) => d.replace(/-?\d+(\.\d+)?/g, (n) => String(Math.round(Number(n))));

const land = [];
const picked = {};

for (const f of countries.features) {
  const name = f.properties.name;
  if (name === 'Antarctica') continue; // adds bulk, says nothing here
  const d = path(f);
  if (!d) continue;
  if (HIGHLIGHT[name]) {
    const [cx, cy] = path.centroid(f);
    picked[HIGHLIGHT[name]] = {
      name,
      d: shrink(d),
      c: [Math.round(cx), Math.round(cy)]
    };
  } else {
    land.push(d);
  }
}

const missing = Object.values(HIGHLIGHT).filter((c) => !picked[c]);
if (missing.length) {
  console.error('MISSING:', missing.join(', '));
  process.exit(1);
}

const landPath = shrink(land.join(' '));
const sphere = shrink(path({ type: 'Sphere' }));

const out = `/* Generated by scripts/genworld.mjs. Do not edit by hand.
   Geometry: Natural Earth 110m (public domain) via world-atlas,
   projected with geoNaturalEarth1 and rounded to 0.1 units. */

export const MAP_WIDTH = ${WIDTH};
export const MAP_HEIGHT = ${HEIGHT};

export const SPHERE_PATH =
  '${sphere}';

export const LAND_PATH =
  '${landPath}';

export interface Country {
  code: string;
  name: string;
  /** SVG path in the 960x500 projection. */
  d: string;
  /** Projected centroid, for anchoring the callout. */
  c: [number, number];
}

export const HIGHLIGHTED: Country[] = [
${Object.entries(picked)
  .map(
    ([code, v]) =>
      `  { code: '${code}', name: ${JSON.stringify(v.name)}, c: [${v.c[0]}, ${v.c[1]}], d: '${v.d}' }`
  )
  .join(',\n')}
];
`;

process.stdout.write(out);
